### ISSUE TITLE
npm run dev  启动报错

### ISSUE THREAD

**Issue by shuch** [mantou132/mt-music-player#17]
`mt-music-player git:(master) npm run dev

> mt-music-player@0.0.2 dev /Users/shuchen/study/web-components/mt-music-player
> nodemon --ignore fe/ --inspect --experimental-modules --es-module-specifier-resolution=node ./server/index.js

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect --experimental-modules --es-module-specifier-resolution=node ./server/index.js`
node: bad option: --es-module-specifier-resolution=node
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by mantou132** [comment]
nodejs 更新到12 就好了
